### ISSUE TITLE
null dashboard error

### ISSUE THREAD

**Issue by michaelvp411** [crockpotveggies/tinderbox#110]
Any idea what's going on? Get this error once trying to log in with token

 @7b2kp66bp - Internal server error, for (GET) [/t/null/dashboard] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at views.html.main$.apply(main.template.scala:53) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at views.html.Application.dashboard$.apply(dashboard.template.scala:28) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at controllers.Application$$anonfun$dashboard$1$$anonfun$apply$2.apply(Application.scala:32) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at controllers.Application$$anonfun$dashboard$1$$anonfun$apply$2.apply(Application.scala:30) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.4.jar:na]
[error] application -

**Comment by bahneclaussen** [comment]
same here.

**Comment by swiftraccoon** [comment]
You can bypass the login by providing the token directly.

localhost:9000/t/TINDER_TOKEN_HERE/dashboard

There are still other things that have to be fixed as well, however.
