### ISSUE TITLE
JSON errors everywhere

### ISSUE THREAD

**Issue by PapaCharlie** [crockpotveggies/tinderbox#15]
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] Starting new message analysis task.
[debug] application - [mapdb] Database committer has persisted data to disk.
com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [id, url, main, fileName, extension, processedFiles, shape, crop, ydistance_percent, yoffset_percent, xoffset_percent, xdistance_percent], but found [shape, id, fileName, processedFiles, extension].
java.lang.Exception: Data was not wrapped in a results class. Could not parse.
        at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:109)
        at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] application - [tinderbot] Retrying a troubled supervised task:
Invalid JSON. Needed [status, error], but found [matches, blocks, lists, deleted_lists, last_activity_date].
[info] application - [tinderbot] Received command: run
[ERROR] [02/11/2015 00:08:47.155] [application-akka.actor.default-dispatcher-8] [akka://application/user/TinderBot/BotSupervisor/$c] Invalid JSON. Needed [status, error], but found [matches, blocks, lists, deleted_lists, last_activity_date].
com.codahale.jerkson.ParsingException: Invalid JSON. Needed [status, error], but found [matches, blocks, lists, deleted_lists, last_activity_date].
        at com.codahale.jerkson.ParsingException$.apply(ParsingException.scala:9)
        at com.codahale.jerkson.Parser$class.parse(Parser.scala:88)
        at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
        at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
        at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
        at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115)
        at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [status, error], but found [matches, blocks, lists, deleted_lists, last_activity_date].
        at com.codahale.jerkson.deser.CaseClassDeserializer.deserialize(CaseClassDeserializer.scala:71)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3038)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
        at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
        ... 23 more

[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] created new Facial Check task for token **token**
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] Starting new facial check task.
[warn] application - [tinderbot] No manual yes/no data available, recommendations may be inaccurate.
[debug] application - [tinderbot] created new Recommendation task for token **token**
[debug] application - [tinderbot] created new Message Analysis task for token **token**
[info] application - [tinderbot] Received command: idle
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] New task received for supervision
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new recommendations task.
[warn] application - [tinderbot] Waiting to start automatic Swipes. User needs to make more choices to ensure accuracy.
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] New task received for supervision
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new message analysis task.

Simply running the app (on both windows 8 cygwin and ubuntu) throws endless errors and refuses to load any data on the webpage. Any ideas?

**Comment by crockpotveggies** [comment]
I've noticed that the data structures from the Tinder API change frequently. One of the ways around this could be to create a custom marshaller that only pulls the desired fields for the API models. Right now I'm using strict deserialization via Scala classes. It could be fairly difficult to fix this, no short-term solution.
