### ISSUE TITLE
App crashes upon submission of FB access token and ID

### ISSUE THREAD

**Issue by ldebrouwer** [crockpotveggies/tinderbox#22]
Whenever I enter my FB access token and ID, and submit the form, the app crashes.

I'm on OS X 10.10.2 and use SBT 0.3.17.

Find the error dump listed below:

```
[debug] application - [mapdb] Database committer has persisted data to disk.
null
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3028)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:108)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Uncaught error from thread [play-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3033)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [02/12/2015 18:05:27.078] [play-akka.actor.default-dispatcher-8] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3033)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348) ~[jackson-databind-2.4.4.jar:2.4.4]
```

**Comment by crockpotveggies** [comment]
Check out the Common Errors in the wiki. This is actually caused by a Java version mismatch :)
