### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AppoPro** [crockpotveggies/tinderbox#32]
I tried on local PC and on VPS and i have same error.

application - ! @6l7iogia0 - Internal server error, for (GET) [/t/e1593de5-6a94-4bcd-ad72-e46e47dcaa51/facial/average/no] ->
play.api.Application$$anon$1: Execution exception[[FileNotFoundException: data/54e0a99989e250a2795cd1c0_mean_no_model.gif (No such file or directory)]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.2.jar:2.2.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: java.io.FileNotFoundException: data/54e0a99989e250a2795cd1c0_mean_no_model.gif (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[na:1.7.0_75]
	at java.io.FileInputStream.<init>(FileInputStream.java:146) ~[na:1.7.0_75]
	at play.api.libs.iteratee.Enumerator$.fromFile(Enumerator.scala:573) ~[play-iteratees_2.10-2.2.2.jar:2.2.2]
	at controllers.FacialAnalysis$$anonfun$fetchAverageFace$1$$anonfun$apply$1.apply(FacialAnalysis.scala:26) ~[classes/:na]
	at controllers.FacialAnalysis$$anonfun$fetchAverageFace$1$$anonfun$apply$1.apply(FacialAnalysis.scala:21) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[scala-library-2.10.4.jar:na]

![IMG](https://cloud.githubusercontent.com/assets/6508486/6203947/86e649b0-b539-11e4-87dd-99224b9aeb5b.png)

**Comment by crockpotveggies** [comment]
Just submitted a fix for this. Redirects to a generic image now until your models have enough data to build.
