### ISSUE TITLE
Errors compiling on Linux Ubuntu 12.04 LTS: Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by wnstnsmth** [crockpotveggies/tinderbox#34]
That's what I get at the end of compilation:

```
[info] Compiling 74 Scala sources and 8 Java sources to /home/tgrossen/tinderbox/target/scala-2.10/classes...
[warn] /home/tgrossen/tinderbox/app/utils/tinder/TinderApi.scala:79: play.api.libs.json.JsValue and None.type are unrelated: they will most likely never compare equal
[warn]                 if(res==None || res==null) throw new Exception("Data was not wrapped in a results class. Could not parse.")
[warn]                       ^
[warn] /home/tgrossen/tinderbox/app/utils/tinder/TinderWS.scala:57: class PerRequestConfig in package client is deprecated: see corresponding Javadoc for more information.
[warn]         val config = new PerRequestConfig()
[warn]             ^
[warn] /home/tgrossen/tinderbox/app/utils/tinder/TinderWS.scala:57: class PerRequestConfig in package client is deprecated: see corresponding Javadoc for more information.
[warn]         val config = new PerRequestConfig()
[warn]                          ^
[warn] there were 19 feature warning(s); re-run with -feature for details
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/DoubleFormat : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/SparseMatrix : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/SparseVector : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/MarkovClustering : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: controllers/routes$javascript : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: controllers/routes$ref : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/ImageNormalizer : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/Vectors : Unsupported major.minor version 51.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: utils/mcl/ExpDouble : Unsupported major.minor version 51.0
[success] Total time: 84 s, completed Feb 15, 2015 8:37:09 PM
```

And when I start the app with `sbt run`, everything seems fine, until I open up 0.0.0.0:9000 in the browser, then I get this in the console: 

```
java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at views.html.Application.index$.apply(index.template.scala:28)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[debug] application - [mapdb] Database committer has persisted data to disk.
java.lang.UnsupportedClassVersionError: controllers/routes
	at views.html.Application.index$.apply(index.template.scala:28)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The app doesn't appear in the browser. Seems related to the compilation warnings, doesn't it?

**Comment by wnstnsmth** [comment]
Turned out I had two versions of java installed on my system (openjdk-6-* and openjdk-7-*). I just removed the former and it worked.

**Comment by ArtFeel** [comment]
I have the same error on Mac OS X 10.10.2 using OSX app launcher.
