### ISSUE TITLE
Errors at start and then failure later

### ISSUE THREAD

**Issue by monksy** [crockpotveggies/tinderbox#35]
At the start of the application I'm getting the following exception:

    [info] application - Creating new session for xAuthToken -------
    java.lang.ExceptionInInitializerError
        at     controllers.FacialAnalysis$$anonfun$checkModelValidity$1$$anonfun$apply$3.apply(FacialAnalysis.scala:65)
            at     controllers.FacialAnalysis$$anonfun$checkModelValidity$1$$anonfun$apply$3.apply(FacialAnalysis.scala:61)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 334620
        at org.mapdb.EncryptionXTEA.decryptBlock(EncryptionXTEA.java:105)
        at org.mapdb.EncryptionXTEA.decrypt(EncryptionXTEA.java:76)
        at org.mapdb.Store.deserialize(Store.java:269)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:368)
        at org.mapdb.StoreWAL.get(StoreWAL.java:352)
        at org.mapdb.Caches$HashTable.get(Caches.java:245)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
        at org.mapdb.DB.getTreeMap(DB.java:788)
        at services.FacialAnalysisService$.<init>(FacialAnalysisService.scala:43)

Later I'll get this error before it completely stops:

    [debug] application - [tinderbot] Starting new facial check task.
    Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
    java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$
        at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    [ERROR] [02/16/2015 01:19:01.099] [application-akka.actor.default-dispatcher-3]     [ActorSystem(application)] Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
    java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$
        at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at     akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by crockpotveggies** [comment]
Can you provide some details about the machine running the code? (Is it Windows? What version? How much RAM? etc.)

My gut feeling is this is either:
1) A bug in MapDB, which unfortunately can't be fixed within the scope of this code
2) Java isn't initializing properly and isn't loading all of the necessary classes to run the code
3) You've edited the code while the process is running, which may have forced it to re-load and something went wrong in the process

**Comment by monksy** [comment]
It is Arch linux under the 3.18.4-1-ARCH kernel. 

Java version:
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

RAM: 8GB total.

What is going on. I am running this by: sbt run. 

No code is being modified at runtime. 

Results of git status:
On branch master                                                                                                                                                                                                                                                                
Your branch is up-to-date with 'origin/master'.                                                                                                                                                                                                                                 
nothing to commit, working directory clean  

No commits are queued and it is up to date as of writing.

**Comment by crockpotveggies** [comment]
I've created a distribution JAR of Tinderbox to eliminate SBT from the equation. Hopefully this simplifies how things are running in the JVM and problems with classes not being loaded into the classpath. Going to close this issue (and a few others related to it).

**Comment by monksy** [comment]
I'm still getting the same errors as before on the the new package 

I ran the new dist via the root path: ./dist/tinderbox-1.1-SNAPSHOT/bin/tinderbox

**Comment by monksy** [comment]
Also this also happens after the session has been authenticated.

**Comment by crockpotveggies** [comment]
Can you try deleting your `data` directory and running again? You'll have to re-build your models, but it looks like some sort of corruption in the MapDB database.
