### ISSUE TITLE
java.lang.IllegalAccessError: already closed

### ISSUE THREAD

**Issue by gonchs** [crockpotveggies/tinderbox#45]
[warn] application - [tinderbot] TinderBot is under pressure (tasks queue > 500)
[warn] application - [tinderbot] TinderBot is under pressure (tasks queue > 500)
Uncaught error from thread [application-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at org.mapdb.DataOutput2.ensureAvail(DataOutput2.java:56)
	at org.mapdb.DataOutput2.write(DataOutput2.java:74)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:401)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
	at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:397)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreWAL.update(StoreWAL.java:403)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.FacialAnalysisService$.appendNoPixels(FacialAnalysisService.scala:129)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(FacialAnalysisTask.scala:52)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(FacialAnalysisTask.scala:42)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(FacialAnalysisTask.scala:42)
	at models.bot.task[ERROR] [02/21/2015 13:44:31.745] [application-akka.actor.default-dispatcher-8] [ActorSystem(application)] Uncaught error from thread [application-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at org.mapdb.DataOutput2.ensureAvail(DataOutput2.java:56)
	at org.mapdb.DataOutput2.write(DataOutput2.java:74)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:401)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
	at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:397)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreWAL.update(StoreWAL.java:403)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.FacialAnalysisService$.appendNoPixels(FacialAnalysisService.scala:129)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(FacialAnalysisTask.scala:52)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(FacialAnalysisTask.scala:42)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$s.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(FacialAnalysisTask.scala:38)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisTask.scala:38)
$anonfun$applyOrElse$2.apply(FacialAnalysisTask.scala:42)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(FacialAnalysisTask.scala:38)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at models.bot.tasks.FacialAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisTask.scala:38)

[info] play - Shutdown application default Akka system.
[INFO] [02/21/2015 13:44:31.788] [application-akka.actor.default-dispatcher-5] [akka://application/user/TinderBot] Message [models.bot.BotCommand] from Actor[akka://application/user/TinderBot/BotSupervisor/$o#-1895060485] to Actor[akka://application/user/TinderBot#-1284459761] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/21/2015 13:44:37.009] [application-akka.actor.default-dispatcher-5] [akka://application/user/UpdatesTask] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/UpdatesTask#-1697730095] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/21/2015 13:44:41.189] [application-akka.actor.default-dispatcher-11] [akka://application/user/DBCommitter] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/DBCommitter#45778638] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.BTreeMap.get(BTreeMap.java:595)
	at org.mapdb.BTreeMap.get(BTreeMap.java:589)
	at services.UpdatesService$.fetchNotifications(UpdatesService.scala:260)
	at services.UpdatesService$.fetchUpdates(UpdatesService.scala:226)
	at controllers.Messaging$$anonfun$updates$1$$anonfun$15.apply(Messaging.scala:90)
	at controllers.Messaging$$anonfun$updates$1$$anonfun$15.apply(Messaging.scala:90)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[warn] application - [recommendations] Could not yet build face models for user 5324f1084f17a70722002785 because:
java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:660)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:225)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by crockpotveggies** [comment]
Tinderbox is leaking memory. Might be caused by the your machine going to sleep and the main thread getting thrown off somehow. Unfortunately, not much I can do on this one for a while. Will have to get back to you.

**Comment by robthegentleman** [comment]
@crockpotveggies sorry I know you didn't sign up for this constant support... but any update on this? I'm running into the same problem. I open Tinderbox up, it runs with "tasks in queue > 500", does it's thing for about 20 mins, then arrives at this every time:


[warn] application - [recommendations] Could not yet build face models for user 52c25332aad8d4a734000962 because: 
java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:660)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:225)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [02/27/2015 08:59:11.414] [application-akka.actor.default-dispatcher-2] [akka://application/user/FaceAnalysisService] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/FaceAnalysisService#-829294885] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/27/2015 08:59:11.414] [application-akka.actor.default-dispatcher-2] [akka://application/user/FaceAnalysisService] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/FaceAnalysisService#-829294885] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/27/2015 08:59:11.414] [application-akka.actor.default-dispatcher-2] [akka://application/user/FaceAnalysisService] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/FaceAnalysisService#-829294885] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/27/2015 08:59:11.414] [application-akka.actor.default-dispatcher-2] [akka://application/user/FaceAnalysisService] Message [java.lang.String] from Actor[akka://application/deadLetters] to Actor[akka://application/user/FaceAnalysisService#-829294885] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

** I should also add that Tinderbox seems to be running the same tasks over and over again each time I close and re-open the application. For example, each time I boot it back up, it starts with the same "Sentiment for match with Nikki-Leigh was POSITIVE"

**Comment by robthegentleman** [comment]
I also deleted a ton of my old matches thinking that would help the tasks queue # go down, but hasn't seemed to help.
