### ISSUE TITLE
Not a valid class file

### ISSUE THREAD

**Issue by iamrekcah** [crockpotveggies/tinderbox#58]
There are more logs to this, but I don't know where this error starts or ends. It also spits out the raw JSON somewhere in between these errors. Maybe Tinder changed its API? 

I'll take a look at it if you can point me in the right direction.

```
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] Starting new message analysis task.
[error] application - 

! @6lem74aeh - Internal server error, for (GET) [/t/cda84d3b-c8d7-490c-8060-b2a7f973a524/profile] ->

play.api.Application$$anon$1: Execution exception[[ScalaSigParserError: Unexpected error: Not a valid class file]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.2.jar:2.2.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: com.codahale.jerkson.util.scalax.rules.ScalaSigParserError: Unexpected error: Not a valid class file
	at com.codahale.jerkson.util.scalax.rules.Rules$$anonfun$expect$1.apply(Rules.scala:63) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.util.scalax.rules.scalasig.ClassFileParser$.parse(ClassFileParser.scala:114) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.util.CaseClassSigParser$.parseClassFileFromByteCode(CaseClassSigParser.scala:24) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.util.CaseClassSigParser$.parseScalaSig(CaseClassSigParser.scala:43) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.util.CaseClassSigParser$.findSym(CaseClassSigParser.scala:56) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.util.CaseClassSigParser$.parse(CaseClassSigParser.scala:83) ~[jerkson_2.10-0.6.3.jar:0.6.3]
null
com.codahale.jerkson.util.scalax.rules.ScalaSigParserError: Unexpected error: Not a valid class file
	at com.codahale.jerkson.util.scalax.rules.Rules$$anonfun$expect$1.apply(Rules.scala:63)
	at com.codahale.jerkson.util.scalax.rules.scalasig.ClassFileParser$.parse(ClassFileParser.scala:114)
	at com.codahale.jerkson.util.CaseClassSigParser$.parseClassFileFromByteCode(CaseClassSigParser.scala:24)
	at com.codahale.jerkson.util.CaseClassSigParser$.parseScalaSig(CaseClassSigParser.scala:43)
	at com.codahale.jerkson.util.CaseClassSigParser$.findSym(CaseClassSigParser.scala:56)
	at com.codahale.jerkson.util.CaseClassSigParser$.parse(CaseClassSigParser.scala:83)
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:17)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3028)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:108)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] application - [tinderbot] Retrying a troubled supervised task: 
Unexpected error: Not a valid class file
```

**Comment by crockpotveggies** [comment]
My guess is that Tinder changed its API. I've never seen this before in the 2+ years working with Jackson and Jerkson. Sorry not sure I'm going to be much help.

I found this with a simple search: https://groups.google.com/forum/#!topic/scala-user/0GsO0Hv9yfA

It looks like it could also happen with a Java version mismatch (Tinderbox was tested with Java7).

**Comment by iamrekcah** [comment]
Turns out I was using OpenJDK 8. I really didn't think forward-compatibility would be a problem. -_-
