### ISSUE TITLE
Java problem when starting the server

### ISSUE THREAD

**Issue by keviin55** [crockpotveggies/tinderbox#66]
I am not able to start the server. I am working with OSX Yosemite. 

MBP-de-monmac:tinderbox-master kevin$ sudo bash lib/fetch_nlp_models
Password:
MBP-de-monmac:tinderbox-master kevin$ sudo bash dist/tinderbox-1.1-SNAPSHOT/bin/tinderbox
Play server process ID is 4083
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/kevin/Downloads/tinderbox-master/dist/tinderbox-1.1-SNAPSHOT/lib/ch.qos.logback.logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/kevin/Downloads/tinderbox-master/dist/tinderbox-1.1-SNAPSHOT/lib/org.slf4j.slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Starting application default Akka system.
[info] application - [tinderbot] TinderBot has started up
[debug] application - [tinderbot] Bot supervisor has started up
[INFO] [03/31/2015 23:45:19.587] [application-akka.actor.default-dispatcher-2] [akka://application/user/TinderBot/BotThrottle] [throttle] monitoring reports will be sent to Some(Actor[akka://application/user/TinderBot#-1482568386])
[info] application - [tinderbot] Received command: run

     |__________________`s__________________
     |__________________s$______________s___
     |_________________.s$$_____________s$__
     |________________s$$$?______s_____s$?__
     |______________.s$$$___ __.s$,___s$$?__
     |_____________s$$$$?______.s$___.$$?___
     |________,____$$$$$.______s$?____?$____
     |________$___$$$$$$s_____s$?_____?,____
     |_______s$___?$$$$$$$s___$$$,____..____
     |_______$$____?$$$$$$s.__?$$s_____,,___
     |________?$.____?$$$$$$$s_.s$$$________
     |_______`$$.____?$$$$$$$_$$$$__ s?_____
     |________?$$s____?$$$$$$s$$$?__ s$?____
     |_________?$$s____$$$$$s$$$$`__ s$$____
     |______s.__$$$$___s$$$$$$$$?_.s $$?____
     |______$$_s$$$$..s$$$$$$$$$$$$$ $?_____
     |______s$.s$$$$s$$$$$$$$$$$$$$$ $______
     |______________________________________
     |
     |    Tinderbox
     |    ===============================
     |    A handy tool for automating and
     |    analyzing the Tinder App
      
        
  
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at views.html.Application.index$.apply(index.template.scala:28)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.

**Comment by crockpotveggies** [comment]
This has been added to the *Common Errors* section in the wiki: https://github.com/crockpotveggies/tinderbox/wiki/Common-Errors#javalangunsupportedclassversionerror-controllersroutes--unsupported-majorminor-version-510

Closing.
