### ISSUE TITLE
Getting no feedback from browser to running bot

### ISSUE THREAD

**Issue by Dylan158** [crockpotveggies/tinderbox#67]
I've had tinderbox running for a few days without any problems, but didn't really like the matches it gave me so i cleared the model. And now it seems the browser doesn't give any feedback.  On ocassion i get the following warning. I allready tried it on other computers and with other tinder accounts, so it must be something i'm doing. 

2015-04-03 19:32:11,457 - [WARN] - from application in application-akka.actor.default-dispatcher-2 
[recommendations] Could not yet build face models for user 550cbb5f34e19d2f1a484201 because: 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at services.FacialAnalysisService$.computeAverageFace(FacialAnalysisService.scala:184)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:222)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by crockpotveggies** [comment]
Need to make more manual selections until the bot tells you it has re-processed your models. Keep using the web interface (note: not the mobile app) to re-train the bot until it starts auto-processing. Also, it takes a while for it to process all of your selections so do not turn off the bot in the background.

**Comment by Dylan158** [comment]
ive made about 300-500 selections and let it run the whole night, but nothing happened.

**Comment by crockpotveggies** [comment]
Last thing I can suggest is a restart.

**Comment by Dylan158** [comment]
Allready done so, ran it on different computers too and with different tinder accounts.

This is how the log looks.

2015-04-04 08:13:36,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] Starting new recommendations task.

2015-04-04 08:13:36,348 - [WARN] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] Waiting to start automatic Swipes. User needs to make more choices to ensure accuracy.

2015-04-04 08:13:36,348 - [INFO] - from application in application-akka.actor.default-dispatcher-1226 
[tinderbot] Received command: run

2015-04-04 08:13:38,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1226 
[tinderbot] New task received for supervision

2015-04-04 08:13:38,348 - [INFO] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] Received command: idle

2015-04-04 08:13:38,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1214 
[tinderbot] Starting new message analysis task.

2015-04-04 08:13:38,583 - [INFO] - from application in application-akka.actor.default-dispatcher-1214 
[tinderbot] Received command: run

2015-04-04 08:13:50,645 - [WARN] - from application in application-akka.actor.default-dispatcher-1225 
[recommendations] Could not yet build face models for user 550cbb5f34e19d2f1a484201 because: 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at services.FacialAnalysisService$.computeAverageFace(FacialAnalysisService.scala:184)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:222)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


2015-04-04 08:13:54,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] created new Facial Check task for token 3d1154e9-7b4d-4170-ac41-b029dbcaf2d2

2015-04-04 08:13:54,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1221 
[tinderbot] New task received for supervision

2015-04-04 08:13:54,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] created new Recommendation task for token 3d1154e9-7b4d-4170-ac41-b029dbcaf2d2

2015-04-04 08:13:54,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1221 
[tinderbot] Starting new facial check task.

2015-04-04 08:13:54,348 - [DEBUG] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] created new Message Analysis task for token 3d1154e9-7b4d-4170-ac41-b029dbcaf2d2

2015-04-04 08:13:54,348 - [WARN] - from application in application-akka.actor.default-dispatcher-1221 
[tinderbot] No manual yes/no data available, recommendations may be inaccurate.

2015-04-04 08:13:54,348 - [INFO] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] Received command: idle

2015-04-04 08:13:54,348 - [INFO] - from application in application-akka.actor.default-dispatcher-1225 
[tinderbot] Received command: run

**Comment by crockpotveggies** [comment]
For whatever reason your choices aren't saving, since that error points to a line of code that references existing data. Last thing I can think of is for you to pull the latest code. Just a heads up there's an existing messaging bug on master. Can't think of anything else.

**Comment by mwittwer** [comment]
I have exactly the same problem. Pulled code two days ago, so it is the latest code.

**Comment by crockpotveggies** [comment]
Last resort: does a fresh start from scratch work?

**Comment by mwittwer** [comment]
Restarting the server didn't work. Deleting the eigenface model also didn't work. Anything else I can try out? (I did basically a fresh start two days ago, because it was the first time I downloaded tinderbox).

**Comment by crockpotveggies** [comment]
Can't think of anything at the moment except that there was an old commit from months ago that caused this same bug. If I have some extra time in the next week I'll dig it up and compare with the master HEAD to see if it was reverted somehow.

**Comment by mwittwer** [comment]
Great, thx.
