### ISSUE TITLE
OOM Java heap space error and missing pixel sets for no models

### ISSUE THREAD

**Issue by aroyer** [crockpotveggies/tinderbox#74]
keep getting OOM java heap error. running on JVM 1.8 and JRE 1.8 anyone else using the latest or is all optimized for 1.7?
```
[warn] application - [recommendations] Could not yet build face models for user 53c0befa72fb97bf5d8e05d8 because: 
java.lang.OutOfMemoryError: Java heap space
	at cern.colt.matrix.impl.DenseDoubleMatrix2D.<init>(Unknown Source)
	at cern.colt.matrix.impl.DenseDoubleMatrix2D.zMult(Unknown Source)
	at cern.colt.matrix.impl.DenseDoubleMatrix2D.zMult(Unknown Source)
	at utils.face.MatrixHelpers$.computeEigenVectors(MatrixHelpers.scala:108)
	at utils.face.EigenFaces$.computeEigenFaces(EigenFaces.scala:24)
	at services.FacialAnalysisService$.computeAverageFace(FacialAnalysisService.scala:210)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:223)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by aroyer** [comment]
moved to digital ocean ubuntu box with java 1.7 and it seems to be working fine. could be an issue with java 1.8 or some issue on my local mac.

**Comment by AlecZadikian9001** [comment]
But I get "unsupported version" if I use Java 1.7, so I can't do that... Any way to launch it with more Java heap space? I can give it all it needs.
