### ISSUE TITLE
Error login / access?

### ISSUE THREAD

**Issue by cbeneyto** [crockpotveggies/tinderbox#75]
Hi! I have errors to try log in in Tinderbox.

This is my console log.

```
[error] play - Cannot invoke the action, eventually got an error: com.codahale.jerkson.ParsingException: Invalid JSON. Needed [status, error], but found [code, error].
[error] application - 

! @6maeam652 - Internal server error, for (POST) [/authenticate] ->

play.api.Application$$anon$1: Execution exception[[ParsingException: Invalid JSON. Needed [status, error], but found [code, error].]]
	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
Caused by: com.codahale.jerkson.ParsingException: Invalid JSON. Needed [status, error], but found [code, error].
	at com.codahale.jerkson.ParsingException$.apply(ParsingException.scala:9) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:88) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [status, error], but found [code, error].
	at com.codahale.jerkson.deser.CaseClassDeserializer.deserialize(CaseClassDeserializer.scala:71) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3038) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
```

**Comment by cbeneyto** [comment]
nope?
