### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by nemanjan00** [crockpotveggies/tinderbox#81]
I have no idea what problem is... 

```
╭─nemanjan00@nemanjan00-laptop  ~/tinderbox  ‹master› 
╰─$ bash dist/tinderbox-1.1-SNAPSHOT/bin/tinderbox                                                                                                                                          130 ↵
    Play server process ID is 4611
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/nemanjan00/tinderbox/dist/tinderbox-1.1-SNAPSHOT/lib/ch.qos.logback.logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/nemanjan00/tinderbox/dist/tinderbox-1.1-SNAPSHOT/lib/org.slf4j.slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Starting application default Akka system.
[debug] application - [tinderbot] Bot supervisor has started up
[info] application - [tinderbot] TinderBot has started up
[INFO] [08/29/2015 11:35:32.530] [application-akka.actor.default-dispatcher-3] [akka://application/user/TinderBot/BotThrottle] [throttle] monitoring reports will be sent to Some(Actor[akka://application/user/TinderBot#-1028326278])
[info] application - [tinderbot] Received command: run


     |__________________`s__________________
     |__________________s$______________s___
     |_________________.s$$_____________s$__
     |________________s$$$?______s_____s$³__
     |______________.s$$$___ __.s$,___s$$³__
     |_____________s$$$$³______.s$___.$$³___
     |________,____$$$$$.______s$³____³$____
     |________$___$$$$$$s_____s$³_____³,____
     |_______s$___³$$$$$$$s___$$$,____..____
     |_______$$____³$$$$$$s.__³$$s_____,,___
     |________³$.____³$$$$$$$s_.s$$$________
     |_______`$$.____³$$$$$$$_$$$$__ s³_____
     |________³$$s____³$$$$$$s$$$³__ s$³____
     |_________³$$s____$$$$$s$$$$`__ s$$____
     |______s.__$$$$___s$$$$$$$$³_.s $$³____
     |______$$_s$$$$..s$$$$$$$$$$$$$ $³_____
     |______s$.s$$$$s$$$$$$$$$$$$$$$ $______
     |______________________________________
     |
     |    Tinderbox
     |    ===============================
     |    A handy tool for automating and
     |    analyzing the Tinder App



[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[debug] application - [mapdb] Database committer has persisted data to disk.
java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at views.html.Application.index$.apply(index.template.scala:28)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.UnsupportedClassVersionError: controllers/routes
    at views.html.Application.index$.apply(index.template.scala:28)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[debug] application - [mapdb] Database committer has persisted data to disk.
```

**Comment by ThisIsGettingWeird** [comment]
Wrong java version I think. Need to use JDK7. maybe even uninstall 8

**Comment by nemanjan00** [comment]
I use jdk7

	╭─nemanjan00@nemanjan00-laptop  ~  
	╰─$ yaourt jdk                                                                                                                                                                              130 ↵
	1 extra/jdk7-openjdk 7.u85_2.6.1-1 [installed]
	    OpenJDK Java 7 development kit
	2 extra/jdk8-openjdk 8.u60-1
	    OpenJDK Java 8 development kit
	3 extra/jre7-openjdk 7.u85_2.6.1-1 [installed]
	    OpenJDK Java 7 full runtime environment
	4 extra/jre7-openjdk-headless 7.u85_2.6.1-1 [installed]

**Comment by nemanjan00** [comment]
╭─nemanjan00@nemanjan00-laptop  /usr/lib/jvm/java-7-openjdk/bin  
	╰─$ java -version                                
	java version "1.7.0_85"
	OpenJDK Runtime Environment (IcedTea 2.6.1) (Arch Linux build 7.u85_2.6.1-1-x86_64)
	OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

**Comment by monksy** [comment]
52 is for Java 8. You need to compile this under JDK8.

**Comment by crockpotveggies** [comment]
Hi everyone,

I'm following up from my previous comments on issues earlier this year. I promised to keep everyone in the loop on the successor to this prototype project, and it's now available. Bernie A.I. is now live in the App Store, and you're welcome to give it a try. A lot more effort has been put into making Bernie work, and it's going to be a lot more convenient.

https://itunes.apple.com/us/app/bernie-a.i./id1068738111

You're still welcome to keep using Tinderbox, I have no plans to remove the Github project. Please keep in mind it is no longer supported.

Warmly,
Justin

**Comment by nemanjan00** [comment]
I do not really care about this anymore, so, I am closing this issue.
