### ISSUE TITLE
Java Issue on MAC OSx

### ISSUE THREAD

**Issue by Mango200** [crockpotveggies/tinderbox#84]
java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at views.html.Application.index$.apply(index.template.scala:28)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm running on java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
logout

I've tried 1.7.0_80, 1.8 and few others, but all keep with this error, which version do I actually use and can I get a download link?

**Comment by uriva** [comment]
+1

**Comment by haohcraft** [comment]
+1

**Comment by AlecZadikian9001** [comment]
It's working with the latest Java 1.8 for me. Doesn't work with 1.7.

**Comment by crockpotveggies** [comment]
Hi everyone,

A friendly reminder that I fully dropped support for Tinderbox before the new year. Feel free to leave these issues open if others from the community want to help out.

Tinderbox is being succeeded by http://www.bernie.ai/ which is entering Alpha this week. You're more than welcome to join the Alpha test group by signing up for the waitlist and then sending a message to help@bernie.ai.

Thanks,
Justin

**Comment by Mango200** [comment]
Fixed This ;)
