### ISSUE TITLE
Null Pointer error

### ISSUE THREAD

**Issue by ghego** [crockpotveggies/tinderbox#85]
I keep seeing this error:

```
    [ERROR] [09/15/2015 15:41:49.931] [application-akka.actor.default-dispatcher-36] [akka://application/user/UpdatesTask] null
    java.lang.NullPointerException
        at services.UpdatesService$.services$UpdatesService$$syncUpdates(UpdatesService.scala:103)
        at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
        at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at services.UpdatesService$UpdatesTask$$anonfun$receive$1.applyOrElse(UpdatesService.scala:49)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

any ideas?

**Comment by jgujgu** [comment]
I'm getting that too. No idea.

**Comment by nick-bull** [comment]
+1

**Comment by pasviegas** [comment]
:(

**Comment by pasviegas** [comment]
So, sometimes the UpdateService gets empty responses, you just need to skip processing when it happens

**Comment by JTatum95** [comment]
I'm getting this same error. All of the pages except dashboard and discovery load for a second and then everything but the taskbar on the side disappears. Did anyone figure this out?
