### ISSUE TITLE
Runtime error when I enter the app?

### ISSUE THREAD

**Issue by erogol** [crockpotveggies/tinderbox#93]
This is what I got;

```
java.lang.UnsupportedClassVersionError: controllers/routes : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at views.html.Application.index$.apply(index.template.scala:28)
        at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
        at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.UnsupportedClassVersionError: controllers/routes
        at views.html.Application.index$.apply(index.template.scala:28)
        at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
        at controllers.Application$$anonfun$index$1$$anonfun$2.apply(Application.scala:21)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I used both 6 and 7 version of openjdk but still I have the same problem. Any idea for the solution ?

**Comment by tranvictor** [comment]
Installing java 8 oracle should fix the problem, also make sure you update your JAVA_HOME.

**Comment by crockpotveggies** [comment]
Hi everyone,

I'm following up from my previous comments on issues earlier this year. I promised to keep everyone in the loop on the successor to this prototype project, and it's now available. Bernie A.I. is now live in the App Store, and you're welcome to give it a try. A lot more effort has been put into making Bernie work, and it's going to be a lot more convenient.

https://itunes.apple.com/us/app/bernie-a.i./id1068738111

You're still welcome to keep using Tinderbox, I have no plans to remove the Github project. Please keep in mind it is no longer supported.

Warmly,
Justin
