### ISSUE TITLE
Error cant fetch details from tinder

### ISSUE THREAD

**Issue by yunesco** [crockpotveggies/tinderbox#95]
[debug] application - [updates] Fetching updates from Tinder API
[error] application - [tinderbot] Retrying a troubled supervised task: 
Futures timed out after [30 seconds]
[info] application - [tinderbot] Received command: run
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] Starting new message analysis task.
[ERROR] [08/06/2016 01:57:45.731] [application-akka.actor.default-dispatcher-9] [akka://application/user/TinderBot/BotSupervisor/$J] Futures timed out after [30 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
    at scala.concurrent.Await$.result(package.scala:107)
    at services.UpdatesService$.syncHistory(UpdatesService.scala:67)
    at services.UpdatesService$.fetchHistory(UpdatesService.scala:200)
    at models.bot.tasks.MessageAnalysisTask$$anonfun$receive$1.applyOrElse(MessageAnalysisTask.scala:27)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    at akka.actor.ActorCell.invoke(ActorCell.scala:456)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[debug] application - [tinderbot] created new Facial Check task for token dbd1dba8-954d-413c-b14a-5c488234b509
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] created new Recommendation task for token dbd1dba8-954d-413c-b14a-5c488234b509
[debug] application - [tinderbot] created new Message Analysis task for token dbd1dba8-954d-413c-b14a-5c488234b509
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new facial check task.
[warn] application - [tinderbot] No manual yes/no data available, recommendations may be inaccurate.
[info] application - [tinderbot] Received command: run
^C[info] play - Shutdown application default Akka system.
[error] application - 

! @7120d2e9d - Internal server error, for (GET) [/t/dbd1dba8-954d-413c-b14a-5c488234b509/messages] ->

play.api.Application$$anon$1: Execution exception[[TimeoutException: Futures timed out after [30 seconds]]]
    at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$5.block(ExecutionContextImpl.scala:48) ~[org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45) ~[org.scala-lang.scala-library-2.10.4.jar:na]
java.lang.IllegalAccessError: already closed
    at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.get(BTreeMap.java:595)
    at org.mapdb.BTreeMap.get(BTreeMap.java:589)
    at services.UpdatesService$.fetchNotifications(UpdatesService.scala:260)
    at services.UpdatesService$.fetchUpdates(UpdatesService.scala:226)
    at controllers.Messaging$$anonfun$updates$1$$anonfun$15.apply(Messaging.scala:90)
    at controllers.Messaging$$anonfun$updates$1$$anonfun$15.apply(Messaging.scala:90)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by yunesco** [comment]
[error] application - 

! @71210gdpb - Internal server error, for (GET) [/t/dbd1dba8-954d-413c-b14a-5c488234b509/analytics/sentiments] ->

play.api.Application$$anon$1: Execution exception[[TimeoutException: Futures timed out after [30 seconds]]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.2.jar:2.2.2]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.2.jar:2.2.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) [scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) [scala-library-2.10.4.jar:na]
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$5.block(ExecutionContextImpl.scala:48) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45) ~[scala-library-2.10.4.jar:na]
[error] application - 

! @71210h3d9 - Internal server error, for (GET) [/t/dbd1dba8-954d-413c-b14a-5c488234b509/messages] ->

play.api.Application$$anon$1: Execution exception[[TimeoutException: Futures timed out after [30 seconds]]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.2.jar:2.2.2]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.2.jar:2.2.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) [scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) [scala-library-2.10.4.jar:na]
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$5.block(ExecutionContextImpl.scala:48) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45) ~[scala-library-2.10.4.jar:na]
