### ISSUE TITLE
Creating new session for xAuthToken null and Internal server error

### ISSUE THREAD

**Issue by orchestor** [crockpotveggies/tinderbox#96]
I am running the app in Mac OS, have the following issue, any pointer to the solution? 

> [info]
> 
>  application - Creating new session for xAuthToken null
> [error] application - 
> 
> ! @712ehgdgg - Internal server error, for (GET) [/t/null/dashboard] ->
> 
> play.api.Application$$anon$1: Execution exception[[JsonParseException: Unrecognized token 'Unauthorized': was expecting ('true', 'false' or 'null')
>  at [Source: [B@c8f91a3; line: 1, column: 25]]]
>   at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
>   at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
>   at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
>   at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
>   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
>   at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang.scala-library-2.10.4.jar:na]
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Unauthorized': was expecting ('true', 'false' or 'null')
>  at [Source: [B@c8f91a3; line: 1, column: 25]
>   at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
>   at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
>   at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3323) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
>   at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2482) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
>   at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
>   at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[com.fasterxml.jackson.core.jackson-core-2.5.3.jar:2.5.3]
> [debug] application - [mapdb] Database committer has persisted data to disk.

**Comment by Tzikas** [comment]
+1
